name: Fx.ElementSwap
author: vincentbluff
category: Effects
tags: [element, effects]
current: 1.0.2
docs: http://github.com/vincentbluff/Fx.ElementSwap/blob/master/README.md
demo: http://vincentbluff.github.com/Fx.ElementSwap